language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: bvandehei-github
    token:
      secure: 04dcdf0f3d26bd8ecd7ed9cddc7b04441ab9c311
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
